"""APPSTACK layout and logic
 mapping app name and app function to physical/relative path 
 on the server and if login is require
 idea here is the be able to have the code outside apache path 
 { App_name the url post/get: 
   { filename: "python_file":, 
     path: 'path to the file'  
     command:"function to call in python file" 
     security: bool,
     content_type: typicaly text/html  this is used by the http client know the type data that was sent 
     server_cache_on: if true tells the rendering engine not process the app but to send cache result
     server_cache_age: the age in seconds on the cache before the server will render the results. 
     client_cacheability: allows part of app to be set its respons as cacheable and the method used 
     client_cache_age:30:

   }
 }
 idea is to be similar to django urls function without the use of regular expressions to match url to functions
 after the enviroment is setup match_url_to_app is run 
"""
def get_as():
    return {
    'main':{ 'template_stack':'main',
            'filename':'magwerks_main', 
            'path':'.',
            'command':'start' , 
            'security':False,
            'content_type': 'text/html',
            'server_cache_on':False,
            'server_cache_age':0,
            'client_cacheability':'private',
            'cache_age':0,
            },
    '/':{ 'template_stack':'main',
            'filename':'magwerks_main', 
            'path':'.',
            'command':'start' , 
            'security':False,
            'content_type': 'text/html',
            'server_cache_on':False,
            'server_cache_age':0,
            'client_cacheability':'private',
            'cache_age':0,
            },
    'list_cal':{ 'template_stack':'list_cal',
            'filename':'calibration', 
            'path':'.',
            'command':'list_cal' , 
            'security':False,
            'content_type': 'text/html',
            'server_cache_on':False,
            'server_cache_age':0,
            'client_cacheability':'private',
            'cache_age':0,
            },
     'link_to_sales_order':{ 'template_stack':'edit_cal',
            'filename':'calibration', 
            'path':'.',
            'command':'link_to_sales_order' , 
            'security':False,
            'content_type': 'text/html',
            'server_cache_on':False,
            'server_cache_age':0,
            'client_cacheability':'private',
            'cache_age':0,
            },
     'link_item_cert':{ 'template_stack':'edit_cal',
            'filename':'calibration', 
            'path':'.',
            'command':'link_item_cert' , 
            'security':False,
            'content_type': 'text/html',
            'server_cache_on':False,
            'server_cache_age':0,
            'client_cacheability':'private',
            'cache_age':0,
            },
     'new_cal':{ 'template_stack':'edit_cal',
            'filename':'calibration', 
            'path':'.',
            'command':'new_cal' , 
            'security':False,
            'content_type': 'text/html',
            'server_cache_on':False,
            'server_cache_age':0,
            'client_cacheability':'private',
            'cache_age':0,
            },
    'list_procedures':{ 'template_stack':'list_procedures',
            'filename':'calibration', 
            'path':'.',
            'command':'list_procedures' , 
            'security':False,
            'content_type': 'text/html',
            'server_cache_on':False,
            'server_cache_age':0,
            'client_cacheability':'private',
            'cache_age':0,
            },
    'cert_report':{'template_stack':'list_cal',
            'filename':'calibration', 
            'path':'.',
            'command':'get_cert_report' , 
            'security':False,
            'content_type': 'text/html',
            'server_cache_on':False,
            'server_cache_age':0,
            'client_cacheability':'private',
            'cache_age':0,
           },
     'cert_edit':{'template_stack':'edit_cal',
            'filename':'calibration', 
            'path':'.',
            'command':'get_cert_edit' , 
            'security':False,
            'content_type': 'text/html',
            'server_cache_on':False,
            'server_cache_age':0,
            'client_cacheability':'private',
            'cache_age':0,
           },
     'cert_replace':{'template_stack':'edit_cal',
            'filename':'calibration', 
            'path':'.',
            'command':'list_cals' , 
            'security':False,
            'content_type': 'text/html',
            'server_cache_on':False,
            'server_cache_age':0,
            'client_cacheability':'private',
            'cache_age':0,
           },
     'save_cert_header':{'template_stack':'edit_cal',
            'filename':'calibration', 
            'path':'.',
            'command':'submit_cal_save' , 
            'security':False,
            'content_type': 'text/html',
            'server_cache_on':False,
            'server_cache_age':0,
            'client_cacheability':'private',
            'cache_age':0,
           },
     'submit_cal_save':{'template_stack':'edit_cal',
            'filename':'calibration', 
            'path':'.',
            'command':'submit_cal_save' , 
            'security':False,
            'content_type': 'text/html',
            'server_cache_on':False,
            'server_cache_age':0,
            'client_cacheability':'private',
            'cache_age':0,
           },
    'view':{'template_stack':"view", 
            'filename':'blog', 
            'path':'.', 
            'command':'view',
            'security':False,
            'content_type':'text/html',
            'server_cache_on':True,
            'server_cache_age':30,
            'client_cacheability':'private',
            'cache_age':30,    
            },
    'list_category':{'template_stack':"list_cats", 
            'filename':'blog', 
            'path':'.', 
            'command':'list_category',
            'security':False,
            'content_type':'text/html',
            'server_cache_on':True,
            'server_cache_age':30,
            'client_cacheability':'private',
            'client_cache_age':30,
            },
    'search_blog':{
            'template_stack':'list', 
            'filename':'blog', 
            'path':'.', 
            'command':'search',
            'security':False,
            'content_type': 'text/html',
            'server_cache_on':True,
            'server_cache_age':30,
            'client_cacheability':'private',
            'cache_age':30,
            },
    'edit_blog':{'filename':'blog', 
              'template_stack':'blog_editor',
              'path':'.',
              'command':'edit_blog', 
              'security':True,
              'content_type': 'text/html',
              },
    'new_blog':{'filename':'blog', 
              'template_stack':'blog_editor',
              'path':'.',
              'command':'new_blog', 
              'security':True,
              'content_type': 'text/html',
              },
    'save_blog':{'filename':'blog', 
              'template_stack':'view',
              'path':'.',
              'command':'save_blog', 
              'security':True,
              'content_type': 'text/html',
              },
    'blog_comment':{'template_stack':'view',
                    'filename':'blog_comment', 
                    'path':'.',
                    'command':'init', 
                    'security':False,
                    'content_type': 'text/html',
                    },
    'create_account':{'template_stack':'view', 
                      'filename':'ca', 
                      'path':'.', 
                      'command':'init', 
                      'security':True,
                      'content_type': 'text/html',
                    },
    'log_in':{'template_stack':'log_in',
             'filename':'session_controller', 
             'path':'.', 
             'command':'log_in', 
             'security':False,
             'content_type': 'text/html',
             },
    'admin':{'template_stack':'view',
             'filename':'admin', 
             'path':'.', 
             'command':'init', 
             'security':True,
             'content_type': 'text/html',
             },
    'file_view':{'template_stack':'view',
                  'filename':'file_helper', 
                  'path':'.', 
                  'command':'list_files', 
                  'security':False,
                  'content_type': 'text/html',
            },
    'file_upload':{'template_stack':'file',
                  'filename':'file_helper', 
                  'path':'.', 
                  'command':'upload_file', 
                  'security':False,
                  'content_type': 'text/html',
            },
    'error':{'template_stack':'error',
                  'filename':'error', 
                  'path':'.', 
                  'command':'show_errors', 
                  'security':True,
                  'content_type': 'text/html',
            },
}